//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPaymentGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiCredential
    {
        public int CredentialId { get; set; }
        public int MerchantId { get; set; }
        public string Environment { get; set; }
        public string PublishableKey { get; set; }
        public string SecretKeyHash { get; set; }
        public string SecretKeyLastFour { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> RotatedAt { get; set; }
    
        public virtual Merchant Merchant { get; set; }
    }
}
