//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPaymentGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiKey
    {
        public int ApiKeyID { get; set; }
        public int MerchantID { get; set; }
        public byte[] KeyHash { get; set; }
        public string KeyPrefix { get; set; }
        public string Environment { get; set; }
        public bool IsRevoked { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> RevokedAt { get; set; }
    
        public virtual Merchant Merchant { get; set; }
    }
}
