//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPaymentGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public long AuditLogId { get; set; }
        public Nullable<int> InternalUserId { get; set; }
        public Nullable<int> MerchantUserId { get; set; }
        public string ActionType { get; set; }
        public string EntityType { get; set; }
        public string EntityId { get; set; }
        public string Details { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual InternalUser InternalUser { get; set; }
        public virtual MerchantUser MerchantUser { get; set; }
    }
}
