//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPaymentGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplianceDocument
    {
        public int DocumentId { get; set; }
        public int VerificationId { get; set; }
        public string DocumentType { get; set; }
        public string FileStoragePath { get; set; }
        public string Status { get; set; }
        public string RejectionNote { get; set; }
        public System.DateTime UploadedAt { get; set; }
    
        public virtual ComplianceVerification ComplianceVerification { get; set; }
    }
}
