//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPaymentGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplianceVerification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComplianceVerification()
        {
            this.ComplianceDocuments = new HashSet<ComplianceDocument>();
        }
    
        public int VerificationId { get; set; }
        public int MerchantId { get; set; }
        public string LegalStructure { get; set; }
        public string IndustrySector { get; set; }
        public bool IsScumlRequired { get; set; }
        public string Status { get; set; }
        public byte ProgressPercent { get; set; }
        public string RejectionReason { get; set; }
        public Nullable<System.DateTime> SubmittedAt { get; set; }
        public Nullable<System.DateTime> ReviewedAt { get; set; }
        public Nullable<int> ReviewedByInternalUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplianceDocument> ComplianceDocuments { get; set; }
        public virtual Merchant Merchant { get; set; }
        public virtual InternalUser InternalUser { get; set; }
    }
}
