//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPaymentGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FraudFlag
    {
        public int FlagId { get; set; }
        public long TransactionId { get; set; }
        public Nullable<byte> RiskScore { get; set; }
        public string FlagReason { get; set; }
        public string Status { get; set; }
        public Nullable<int> ReviewedByInternalUserId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> ResolvedAt { get; set; }
    
        public virtual InternalUser InternalUser { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
