//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPaymentGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentAttempt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentAttempt()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public long PaymentAttemptId { get; set; }
        public int PaymentRequestId { get; set; }
        public byte AttemptNumber { get; set; }
        public string PaymentMethod { get; set; }
        public string Status { get; set; }
        public string FailureReason { get; set; }
        public string ProviderReference { get; set; }
        public string CardBrand { get; set; }
        public string CardLast4 { get; set; }
        public Nullable<byte> CardExpiryMonth { get; set; }
        public Nullable<short> CardExpiryYear { get; set; }
        public string BankCode { get; set; }
        public string UssdDialString { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> CompletedAt { get; set; }
    
        public virtual PaymentRequest PaymentRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
