//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPaymentGateway.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class paymentgatewaydbEntities : DbContext
    {
        public paymentgatewaydbEntities()
            : base("name=paymentgatewaydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApiCredential> ApiCredentials { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<ComplianceDocument> ComplianceDocuments { get; set; }
        public virtual DbSet<ComplianceVerification> ComplianceVerifications { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<FraudFlag> FraudFlags { get; set; }
        public virtual DbSet<InternalUser> InternalUsers { get; set; }
        public virtual DbSet<MerchantBankAccount> MerchantBankAccounts { get; set; }
        public virtual DbSet<Merchant> Merchants { get; set; }
        public virtual DbSet<MerchantUser> MerchantUsers { get; set; }
        public virtual DbSet<PaymentAttempt> PaymentAttempts { get; set; }
        public virtual DbSet<PaymentRequest> PaymentRequests { get; set; }
        public virtual DbSet<Payout> Payouts { get; set; }
        public virtual DbSet<PayoutTransaction> PayoutTransactions { get; set; }
        public virtual DbSet<Refund> Refunds { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SupportTicket> SupportTickets { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<WalletLedgerEntry> WalletLedgerEntries { get; set; }
        public virtual DbSet<Wallet> Wallets { get; set; }
        public virtual DbSet<WebhookDeliveryLog> WebhookDeliveryLogs { get; set; }
        public virtual DbSet<WebhookEndpoint> WebhookEndpoints { get; set; }
        public virtual DbSet<WebhookSubscription> WebhookSubscriptions { get; set; }
    }
}
