//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPaymentGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentRequest()
        {
            this.PaymentAttempts = new HashSet<PaymentAttempt>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int PaymentRequestId { get; set; }
        public int MerchantId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Reference { get; set; }
        public string IdempotencyKey { get; set; }
        public decimal Amount { get; set; }
        public string Currency { get; set; }
        public string Narration { get; set; }
        public string Status { get; set; }
        public string SelectedPaymentMethod { get; set; }
        public System.DateTime ExpiresAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Merchant Merchant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentAttempt> PaymentAttempts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
