//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPaymentGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayoutTransaction
    {
        public long PayoutTransactionId { get; set; }
        public int PayoutId { get; set; }
        public long TransactionId { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Payout Payout { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
