//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPaymentGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payout()
        {
            this.PayoutTransactions = new HashSet<PayoutTransaction>();
        }
    
        public int PayoutId { get; set; }
        public int MerchantId { get; set; }
        public int BankAccountId { get; set; }
        public string Reference { get; set; }
        public decimal Amount { get; set; }
        public string Status { get; set; }
        public System.DateTime ScheduledFor { get; set; }
        public Nullable<System.DateTime> PaidAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual MerchantBankAccount MerchantBankAccount { get; set; }
        public virtual Merchant Merchant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayoutTransaction> PayoutTransactions { get; set; }
    }
}
