//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPaymentGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refund
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Refund()
        {
            this.WalletLedgerEntries = new HashSet<WalletLedgerEntry>();
        }
    
        public int RefundId { get; set; }
        public long TransactionId { get; set; }
        public decimal Amount { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
        public Nullable<int> RequestedByMerchantUserId { get; set; }
        public Nullable<int> ApprovedByInternalUserId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> ProcessedAt { get; set; }
    
        public virtual InternalUser InternalUser { get; set; }
        public virtual MerchantUser MerchantUser { get; set; }
        public virtual Transaction Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WalletLedgerEntry> WalletLedgerEntries { get; set; }
    }
}
