//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPaymentGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refund
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Refund()
        {
            this.WalletLedgers = new HashSet<WalletLedger>();
        }
    
        public long RefundID { get; set; }
        public long TransactionID { get; set; }
        public string RequestedByUser { get; set; }
        public string ApprovedByUser { get; set; }
        public decimal Amount { get; set; }
        public string StatusCode { get; set; }
        public string Reason { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public Nullable<System.DateTime> CompletedAt { get; set; }
    
        public virtual RefundStatu RefundStatu { get; set; }
        public virtual Transaction Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WalletLedger> WalletLedgers { get; set; }
    }
}
