//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPaymentGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportTicket
    {
        public int TicketId { get; set; }
        public Nullable<int> MerchantId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<long> TransactionId { get; set; }
        public Nullable<int> AssignedInternalUserId { get; set; }
        public string Subject { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> ResolvedAt { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual InternalUser InternalUser { get; set; }
        public virtual Merchant Merchant { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
