//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPaymentGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.Refunds = new HashSet<Refund>();
            this.TransactionStatusHistories = new HashSet<TransactionStatusHistory>();
            this.WalletLedgers = new HashSet<WalletLedger>();
            this.WebhookEvents = new HashSet<WebhookEvent>();
        }
    
        public long TransactionID { get; set; }
        public string TransactionRef { get; set; }
        public int MerchantID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public string IdempotencyKey { get; set; }
        public decimal Amount { get; set; }
        public string Currency { get; set; }
        public decimal FeeAmount { get; set; }
        public string StatusCode { get; set; }
        public string ProcessorName { get; set; }
        public string ProcessorRef { get; set; }
        public string Narration { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Merchant Merchant { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Refund> Refunds { get; set; }
        public virtual TransactionStatu TransactionStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionStatusHistory> TransactionStatusHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WalletLedger> WalletLedgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebhookEvent> WebhookEvents { get; set; }
    }
}
