//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPaymentGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionStatusHistory
    {
        public long HistoryID { get; set; }
        public long TransactionID { get; set; }
        public string FromStatus { get; set; }
        public string ToStatus { get; set; }
        public System.DateTime ChangedAt { get; set; }
        public string Reason { get; set; }
    
        public virtual Transaction Transaction { get; set; }
        public virtual TransactionStatu TransactionStatu { get; set; }
    }
}
