//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPaymentGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletLedgerEntry
    {
        public long LedgerEntryId { get; set; }
        public int WalletId { get; set; }
        public Nullable<long> TransactionId { get; set; }
        public Nullable<int> PayoutId { get; set; }
        public Nullable<int> RefundId { get; set; }
        public string EntryType { get; set; }
        public decimal Amount { get; set; }
        public decimal BalanceAfter { get; set; }
        public string Reason { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Refund Refund { get; set; }
        public virtual Transaction Transaction { get; set; }
        public virtual Wallet Wallet { get; set; }
    }
}
