//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPaymentGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebhookDeliveryLog
    {
        public long DeliveryId { get; set; }
        public int WebhookId { get; set; }
        public string EventType { get; set; }
        public string PayloadJson { get; set; }
        public Nullable<int> ResponseStatusCode { get; set; }
        public byte AttemptNumber { get; set; }
        public bool Success { get; set; }
        public System.DateTime DeliveredAt { get; set; }
    
        public virtual WebhookEndpoint WebhookEndpoint { get; set; }
    }
}
