//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPaymentGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebhookEndpoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebhookEndpoint()
        {
            this.WebhookDeliveryLogs = new HashSet<WebhookDeliveryLog>();
            this.WebhookSubscriptions = new HashSet<WebhookSubscription>();
        }
    
        public int WebhookId { get; set; }
        public int MerchantId { get; set; }
        public string Environment { get; set; }
        public string Url { get; set; }
        public string SigningSecretHash { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Merchant Merchant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebhookDeliveryLog> WebhookDeliveryLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebhookSubscription> WebhookSubscriptions { get; set; }
    }
}
