//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPaymentGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebhookEvent
    {
        public long WebhookEventID { get; set; }
        public string ProcessorName { get; set; }
        public string EventType { get; set; }
        public string ProcessorEventID { get; set; }
        public Nullable<long> TransactionID { get; set; }
        public string Payload { get; set; }
        public bool SignatureValid { get; set; }
        public Nullable<System.DateTime> ProcessedAt { get; set; }
        public string ProcessingError { get; set; }
        public System.DateTime ReceivedAt { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
