//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPaymentGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebhookSubscription
    {
        public int SubscriptionId { get; set; }
        public int WebhookId { get; set; }
        public string EventType { get; set; }
        public bool IsEnabled { get; set; }
    
        public virtual WebhookEndpoint WebhookEndpoint { get; set; }
    }
}
